import { LocationPin } from './types';

export const LOCATION_PINS: LocationPin[] = [
  {
    id: 'park-dukyi-001',
    name: '일산서구 반려동물공원',
    category: 'PARK',
    lat: 37.6882,
    lng: 126.7652,
    address: '고양시 일산서구 경의로 766',
    description: '대형견·소형견 모두 추천. 배변처리 편의 좋음. 야간 이용 가능. 활동량 많은 반려견 추천.',
    dogFriendlyScore: 5,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: false,
    parkingAvailable: true,
    reservationRequired: false,
    leashRequired: true,
    notes: '실제 야간 조명 밝기 양호하며 피크 시간 혼잡도가 다소 있음.'
  },
  {
    id: 'toilet-dukyi-001',
    name: '일산서구 반려동물공원 내 배변처리 지점',
    category: 'TOILET',
    lat: 37.68835,
    lng: 126.76535,
    address: '고양시 일산서구 경의로 766',
    description: '배변봉투 있음 / 쓰레기통 있음 / 산책 시작 전·귀가 전 추천.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: false,
    parkingAvailable: true,
    reservationRequired: false,
    leashRequired: true,
    notes: '배변봉투 수거함 후보 및 공원 가꾸기 핵심 권장 코스.'
  },
  {
    id: 'toilet-dukyi-002',
    name: '탄현공원 배변봉투 수거함',
    category: 'TOILET',
    lat: 37.6974,
    lng: 126.7667,
    address: '탄현공원',
    description: '배변봉투 수거함 후보. 탄현 생활권 산책 중간 경유지로 적합.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: false,
    notes: '공원 입구 기준 보정 좌표.'
  },
  {
    id: 'cafe-dukyi-001',
    name: '카페더공생',
    category: 'CAFE',
    lat: 37.69251493,
    lng: 126.7574248,
    address: '경기 고양시 일산서구 탄중로 111',
    description: '소형견 중심 애견카페. 실내·실외 이용 가능. 산책 후 휴식/보호자 식사 추천.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM',
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: false,
    leashRequired: true,
    notes: '실외 천연잔디 공간 우수. 물그릇 제공 가능.'
  },
  {
    id: 'cafe-dukyi-002',
    name: '테일더블루',
    category: 'CAFE',
    lat: 37.69905311,
    lng: 126.7535758,
    address: '경기 고양시 일산서구 하이파크2로 40 금문프라자',
    description: '소형견 루프탑 애견카페. 실내+야외 공간. 반려견 식사 가능.',
    dogFriendlyScore: 5,
    dogSizeAllowed: 'SMALL',
    indoorAllowed: true,
    parkingAvailable: true,
    leashRequired: true,
    notes: '루프탑 안전 펜스 구비. 프리미엄 반려 식사 메뉴 구비.'
  },
  {
    id: 'store-dukyi-001',
    name: '폴리파크 덕이점',
    category: 'PET_STORE',
    lat: 37.69345,
    lng: 126.76015,
    address: '경기 고양시 일산서구 경의로 847-5',
    description: '24시간 무인 산책용품 보충 장소. 사료·간식·위생용품 구매 후보. 야간 산책 전 경유 추천.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: false,
    leashRequired: true,
    notes: '24시간 키오스크 운영으로 야간 급한 용품 수급에 절대 추천.'
  },
  {
    id: 'store-dukyi-002',
    name: '펫존 덕이점',
    category: 'PET_STORE',
    lat: 37.6951,
    lng: 126.76183,
    address: '경기 고양시 일산서구 경의로 873',
    description: '반려견 동반 입장 가능 용품점. 산책 전 준비/물품 보충 추천.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: false,
    leashRequired: true,
    notes: '용품 다양성 높음. 동반 입장 지원.'
  },
  {
    id: 'store-dukyi-003',
    name: '펫투데이',
    category: 'PET_STORE',
    lat: 37.6968,
    lng: 126.7472,
    address: '경기 고양시 일산서구 덕이동 533-1',
    description: '사료·간식·배변패드 구매 후보. 용품점 보조 핀으로 적합.',
    dogFriendlyScore: 3,
    notes: '목줄 착용 후 동반 가능여부 체크 권장.'
  },
  {
    id: 'hospital-dukyi-001',
    name: '돌봄동물병원',
    category: 'HOSPITAL',
    lat: 37.69915055,
    lng: 126.7539582,
    address: '경기 고양시 일산서구 하이파크2로 42',
    description: '덕이동 하이파크시티권 근처 병원. 정기검진/산책 중 이상 발생 시 후보.',
    dogFriendlyScore: 3,
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: true,
    notes: '친절한 수의진 대기. 주말 예약 권장.'
  },
  {
    id: 'hospital-dukyi-002',
    name: '조이동물병원',
    category: 'HOSPITAL',
    lat: 37.69251493,
    lng: 126.7574248,
    address: '경기 고양시 일산서구 탄중로 111 양우로데오메인타운',
    description: '덕이동 로데오거리권 병원. 카페더공생·펫존 근처 안전망 후보.',
    dogFriendlyScore: 3,
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: true,
    notes: '로데오거리 인접하여 접근성 양호.'
  },
  {
    id: 'park-dukyi-002',
    name: '덕이근린1',
    category: 'PARK',
    lat: 37.701779,
    lng: 126.7544876,
    address: '경기 고양시 일산서구 덕이동 산145-1',
    description: '덕이동 내부 짧은 산책 후보. 보호자 운동 병행 가능.',
    dogFriendlyScore: 3,
    indoorAllowed: false,
    parkingAvailable: false,
    notes: '동네 조용한 흙길 산책 구역.'
  },
  {
    id: 'park-dukyi-003',
    name: '덕이근린2',
    category: 'PARK',
    lat: 37.69601631,
    lng: 126.7494325,
    address: '경기 고양시 일산서구 덕이동 산131-7',
    description: '짧은 동네 산책 보조 후보. 조용한 루트 구성용.',
    dogFriendlyScore: 3,
    notes: '가구 단지 뒤편 조용한 숲마당.'
  },
  {
    id: 'cafe-mojjine-hocance-001',
    name: '모찌네 호캉스',
    category: 'CAFE',
    lat: 37.437092,
    lng: 127.1410013,
    address: '경기 성남시 중원구 산성대로 202 성남빌딩 4층',
    description: '애견카페 겸 애견호텔·놀이방 운영 후보. 1인 입장료 1만원, 매너벨트·예방접종 등 이용 제한 확인 필요.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM',
    indoorAllowed: true,
    parkingAvailable: false,
    reservationRequired: false,
    leashRequired: true,
    notes: '목요일 휴무. 컨디셔닝 놀이방 수시 운영.'
  },
  {
    id: 'hospital-raeon-001',
    name: '래온 동물병원',
    category: 'HOSPITAL',
    lat: 37.4350665,
    lng: 127.1383914,
    address: '경기 성남시 중원구 광명로 89 센트럴푸르지오시티 134, 135호',
    description: '치과·심장초음파·슬개골탈구·피부·수술 진료 후보 동물병원.',
    dogFriendlyScore: 3,
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: true,
    notes: '일요일 정기휴무. 정밀 수술 설비 완비.'
  },
  {
    id: 'store-kangkangpet-taepyeong-001',
    name: '캉캉펫 태평점',
    category: 'PET_STORE',
    lat: 37.44294,
    lng: 127.13583,
    address: '경기 성남시 수정구 탄리로 77 1층',
    description: '사료·간식·옷·리드줄·배변패드·산책용품 등 취급 반려동물 용품점.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL|MEDIUM',
    indoorAllowed: true,
    parkingAvailable: false,
    reservationRequired: false,
    notes: '1, 3째 월요일 휴무. 배변패드 등 다채로운 로컬 브랜드 비치.'
  },
  {
    id: 'store-amudoeopgae-seongnam-sinheung-001',
    name: '아무도없개 성남신흥점',
    category: 'PET_STORE',
    lat: 37.44237478,
    lng: 127.1440902,
    address: '경기 성남시 수정구 시민로156번길 7-1 1층',
    description: '24시간 무인 반려용품 편의점. 수제 간식 전용 쇼케이스 비치.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL|MEDIUM',
    indoorAllowed: true,
    notes: '무인 펫 편의점 중 가장 다양한 간식 구비.'
  },
  {
    id: 'park-seongnam-1st-industrial-park-001',
    name: '제1공단근린공원 및 성남박물관 옥상 반려견놀이터',
    category: 'PARK',
    lat: 37.4468,
    lng: 127.1501,
    address: '경기 성남시 수정구 희망로 475 성남시 박물관',
    description: '성남시 박물관 5층 옥상 반려견놀이터가 위치한 친화형 산책 마당. 소형견 전용.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL',
    indoorAllowed: false,
    parkingAvailable: true,
    notes: '오전 9:30~17:30 운영. 월요일 휴무.'
  },
  {
    id: 'toilet-seongnam-museum-dog-playground-001',
    name: '성남시 박물관 옥상 반려견놀이터 배변봉투함',
    category: 'TOILET',
    lat: 37.44685,
    lng: 127.15015,
    address: '경기 성남시 수정구 희망로 475 성남시 박물관 5층 옥상',
    description: '반려견 놀이터 내 배변봉투함 및 공중 위생 쓰레기통 비치 지역.',
    dogFriendlyScore: 4,
    notes: '공인된 반려 기구로 청결도 최상.'
  },
  {
    id: 'park-yeongjang-001',
    name: '영장근린공원',
    category: 'PARK',
    lat: 37.45115107,
    lng: 127.1380153,
    address: '경기 성남시 수정구 태평동 224-3',
    description: '자연수림대와 산책로가 있는 아름다운 언덕 공원. 그늘막이 많고 상시 개방.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    parkingAvailable: true,
    notes: '목줄 필수 착용 및 맹견 입마개 팻말 완비.'
  },
  {
    id: 'park-seongnam-sports-ssireum-001',
    name: '성남종합운동장 씨름장 녹지',
    category: 'PARK',
    lat: 37.43179484,
    lng: 127.139465,
    address: '경기 성남시 중원구 제일로 60 성남종합운동장',
    description: '성남종합운동장 주차장 씨름장 근교의 숨겨진 잔디 녹지.',
    dogFriendlyScore: 2,
    notes: '공원 지정 구역은 아니나 넓은 공간으로 리프레시하기 적당함.'
  },
  {
    id: 'hospital-cheese-bucheon-001',
    name: '부천 치즈동물병원',
    category: 'HOSPITAL',
    lat: 37.46187,
    lng: 126.8127,
    address: '경기 부천시 소사구 범안로 227 3층 308, 309호',
    description: '정기 검진 및 응급 처장 특화. 고양이와 강아지 대기 공간이 분리되어 낯가림에 뛰어난 병원.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    reservationRequired: true,
    notes: '야간 긴급 진료 응대 가능. 위생 배변 패드 상시 공급.'
  },
  {
    id: 'store-wagthedog-bucheon-001',
    name: '왝더독 부천점',
    category: 'PET_STORE',
    lat: 37.46236,
    lng: 126.8125,
    address: '경기 부천시 소사구 범안로 227 1층 101호',
    description: '24시간 무인 산책 상점. 가슴줄, 하네스, 하이브리드 리드줄 및 친환경 배변 패드 비치.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    notes: '인접 산책로로 나가기 전 들르기 최고.'
  },
  {
    id: 'cafe-tasha-bucheon-001',
    name: '카페타샤 부천소사점',
    category: 'CAFE',
    lat: 37.46938,
    lng: 126.8121,
    address: '경기 부천시 소사구 양지남로 45-1 102호',
    description: '24시간 연중무휴 동반 테마 카페. 대형견 입장이 흔쾌히 수락되며 야외 테이블 구비.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    notes: '실내 3테이블 규모의 포근한 심야 아지트.'
  },
  {
    id: 'park-sandeul-history-culture-001',
    name: '산들역사문화공원',
    category: 'PARK',
    lat: 37.462211,
    lng: 126.8149777,
    address: '경기 부천시 소사구 범안로 225-2 청주한씨청평군파종중',
    description: '약 250m 경사를 두른 고립형 차단 친환경 산책지. 배마루 아래 청결도 최상.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    notes: '공용화장실 내부 쓰레기통 이용 가능.'
  },
  {
    id: 'park-198-neighborhood-bucheon-001',
    name: '198호 근린공원',
    category: 'PARK',
    lat: 37.4694,
    lng: 126.8113,
    address: '경기 부천시 소사구 양지남로 40',
    description: '폭이 500m에 달하는 평지 근린공원. 야간 가로등 시설이 보장되어 안전 마실로 훌륭함.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    notes: '노령견 마차나 휠체어 전용 경사로 구비 완비.'
  },
  {
    id: 'park-dandae-001',
    name: '단대공원',
    category: 'PARK',
    lat: 37.45469643,
    lng: 127.15891032,
    address: '경기 성남시 수정구 단대로16번길 25',
    description: '중소형견이 좋아하는 조붓한 동네 고갯길 공원. 음수대와 벤치 그늘이 많아요.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    notes: '단대역 인접 동네 수풀 산책.'
  },
  {
    id: 'hospital-hue-medical-center-001',
    name: '휴 동물의료센터',
    category: 'HOSPITAL',
    lat: 37.4455,
    lng: 127.1466,
    address: '경기도 성남시 수정구 산성대로 309 고려빌딩 2~3층',
    description: '성남 신흥역 중심의 초대형 24시간 응급 진료 전문 센터.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    parkingAvailable: true,
    notes: '야간 긴급 응진 체계가 매우 잘 잡힌 수정구 대표 병원.'
  },
  {
    id: 'cafe-bandog-001',
    name: 'Ban dog 카페',
    category: 'CAFE',
    lat: 37.4566,
    lng: 127.1284,
    address: '경기도 성남시 수정구 복정로 63-1 4층',
    description: '복정동 전용 루프탑 애견 카페. 넓은 잔디 운동장과 중대형견 크기 무제한 하네스 탈착 구역.',
    dogFriendlyScore: 5,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    indoorAllowed: true,
    notes: '주차 협소하므로 복정동 공영주차장 활용 추천.'
  },
  {
    id: 'park-bokwoomul-001',
    name: '복우물공원',
    category: 'PARK',
    lat: 37.45551308,
    lng: 127.1280969,
    address: '경기 성남시 수정구 복정동 697',
    description: '가천대학교와 복정역 중간의 평화로운 로컬 보석 공원.',
    dogFriendlyScore: 4,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    notes: '흙냄새 충진 최적 코스.'
  },
  {
    id: 'toilet-bokwoomul-001',
    name: '복우물공원 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.45565,
    lng: 127.12825,
    address: '경기 성남시 수정구 복정동 697 인근',
    description: '공원 복판 청소 관리용 친친 위생 가꾸기 편의 구제처.',
    dogFriendlyScore: 3,
    notes: '비닐봉투 휴대 필수 권장.'
  },
  {
    id: 'park-bokjeong-001',
    name: '복정공원',
    category: 'PARK',
    lat: 37.4677109,
    lng: 127.1278633,
    address: '경기 성남시 수정구 복정동 635',
    description: '복정동 주민들의 저녁 홈산책 필수 어귀. 조명이 수시 조광됨.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL|MEDIUM|LARGE',
    notes: '인근 하천 둔치길과 도보 연결.'
  },
  {
    id: 'toilet-bokjeong-park-001',
    name: '복정공원 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.46785,
    lng: 127.12795,
    address: '경기 성남시 수정구 복정동 635 인근',
    description: '복정공원 진입 정자 옆에 위치한 미화 휴식 구멍.',
    dogFriendlyScore: 3,
    notes: '배변봉투 수거 웰컴 수거망 존재.'
  },
  {
    id: 'park-giwatgol-001',
    name: '기왓골어린이공원',
    category: 'PARK',
    lat: 37.46378222,
    lng: 127.1276765,
    address: '경기 성남시 수정구 복정로118번길 7',
    description: '어린이 보호 구역 내의 조용한 보조 쉼터. 노령견과 쉬어가기 탁월.',
    dogFriendlyScore: 3,
    notes: '낮 시간대에는 아기들이 있어 보호 리드 필수.'
  },
  {
    id: 'park-tancheon-gachon-start-001',
    name: '탄천 산책로 가천대 방향 진입점',
    category: 'PARK',
    lat: 37.45055,
    lng: 127.1264,
    address: '가천대역·탄천 인근',
    description: '가천대에서 탄천 산책로로 곧장 미끄러져 내려가는 데크 진입 슬로프.',
    dogFriendlyScore: 4,
    notes: '인도가 분리되어 자전거 통행 방해 없음.'
  },
  {
    id: 'park-tancheon-mid-001',
    name: '탄천 산책로 중간 경유점',
    category: 'PARK',
    lat: 37.4537,
    lng: 127.1268,
    address: '성남시 수정구 탄천 산책로 인근',
    description: '시원한 물빛과 대자연 둔치 바람을 쏘이며 걷는 중간 환적 벤치.',
    dogFriendlyScore: 4,
    notes: '조약돌 지압판과 휴식 마루 비치.'
  },
  {
    id: 'park-tancheon-bokjeong-bridge-001',
    name: '탄천 복정 방향 연결 지점',
    category: 'PARK',
    lat: 37.4584,
    lng: 127.1269,
    address: '복정동 탄천 산책로 인근',
    description: '탄천에서 복정 주거단지와 동서울대로 올라서는 넓적한 경사 교량.',
    dogFriendlyScore: 4,
    notes: '다리 횡단 시 차량이 없어서 매우 안심함.'
  },
  {
    id: 'park-tancheon-taepyeong-001',
    name: '탄천 태평 방향 산책 지점',
    category: 'PARK',
    lat: 37.4445,
    lng: 127.1268,
    address: '태평동 탄천 산책로 인근',
    description: '야간 조명이 시원시원하고 우레탄 도로가 마련되어 관절이 유약한 중서견에 제격.',
    dogFriendlyScore: 4,
    notes: '야간 발광 자전거 반사판 필수 주의.'
  },
  {
    id: 'toilet-tancheon-gachon-001',
    name: '탄천 가천대 방향 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.4499,
    lng: 127.1269,
    address: '가천대역·탄천 산책로 인근',
    description: '가천대 방향 우측 하천길을 따라 비치된 생태 비닐 봉지함.',
    dogFriendlyScore: 3,
    notes: '시 보급 위생 용기함 비치됨.'
  },
  {
    id: 'park-tancheon-wetland-001',
    name: '탄천민물고기습지생태원',
    category: 'PARK',
    lat: 37.44974548,
    lng: 127.1270219,
    address: '경기 성남시 수정구 태평동 탄천 인근',
    description: '수풀 내음과 습지 억새 정치가 동화책 감성이 물씬 돋우는 이국적 습지 공터.',
    dogFriendlyScore: 4,
    notes: '반려견 노끈 필수. 흙길이 다닥다닥 발바닥에 감김.'
  },
  {
    id: 'park-gachon-station-walk-001',
    name: '가천대역 산책 출발 후보 지점',
    category: 'PARK',
    lat: 37.4488,
    lng: 127.1268,
    address: '가천대역 인근',
    description: '가천대역 주변에서 탄천 방향 지반 도로를 여는 펫 웰컴 보도.',
    dogFriendlyScore: 3,
    notes: '차량 유도 연석선 근교.'
  },
  {
    id: 'park-gachon-campus-east-001',
    name: '가천대 동측 산책 연결 지점',
    category: 'PARK',
    lat: 37.4509,
    lng: 127.1287,
    address: '경기 성남시 수정구 성남대로 가천대 인근',
    description: '대학 건물 뒤 화단 녹우를 관람하며 걷는 보도의 코너점.',
    dogFriendlyScore: 3,
    notes: '한가한 주말 시간대 추천.'
  },
  {
    id: 'cafe-tcourse-001',
    name: '티코스커피',
    category: 'CAFE',
    lat: 37.4539,
    lng: 127.1273,
    address: '경기 성남시 수정구 복정로 10',
    description: '펫 프렌들리 스냅 카페. 테라스에서 소형 반려견 동행 착석 가능.',
    dogFriendlyScore: 3,
    dogSizeAllowed: 'SMALL',
    notes: '수제 개껌 간식 샘플 서비스 있음.'
  },
  {
    id: 'cafe-bokjeong-rest-001',
    name: '복정동 카페 휴식 후보 지점',
    category: 'CAFE',
    lat: 37.4562,
    lng: 127.1281,
    address: '경기 성남시 수정구 복정동 690번지 일대',
    description: '반려동물 마실에 후한 개인 로스터리들이 복복이 모인 가로.',
    dogFriendlyScore: 3,
    notes: '방문 전 전화 확인 수반 권장.'
  },
  {
    id: 'cafe-wirye-nearby-001',
    name: '위례 카페 후보 지점',
    category: 'CAFE',
    lat: 37.4680,
    lng: 127.1534,
    address: '경기 성남시 수정구 위례순환로 인근',
    description: '위례 거대 천변 숲거리의 동행 우수 스팟.',
    dogFriendlyScore: 4,
    notes: '소박한 발코니 테이블 구비.'
  },
  {
    id: 'hospital-iple-001',
    name: '이플동물병원',
    category: 'HOSPITAL',
    lat: 37.4564,
    lng: 127.1286,
    address: '경기 성남시 수정구 복정로 35',
    description: '동네 애견인들이 만장일치 친절하다고 꼽는 든든한 일차 의료망 병원.',
    dogFriendlyScore: 3,
    notes: '친밀한 케어가 무척 돋보임.'
  },
  {
    id: 'hospital-taepyeong-station-001',
    name: '태평역 동물병원 후보',
    category: 'HOSPITAL',
    lat: 37.4408,
    lng: 127.1269,
    address: '경기 성남시 수정구 성남대로 1222 인근',
    description: '태평역과 천변 연결부 초입의 안전망 클리닉 후보지.',
    dogFriendlyScore: 3,
    notes: '가벼운 관절 영양 보충 및 비상 물약 수급 용이.'
  },
  {
    id: 'hospital-geonguk-001',
    name: '건국동물병원 후보',
    category: 'HOSPITAL',
    lat: 37.4439,
    lng: 127.1308,
    address: '경기 성남시 수정구 수정로 131 인근',
    description: '태평 생활권 단짝 병원의 상시 안전 수집 지점.',
    dogFriendlyScore: 3,
    notes: '로컬 애용 빈도 높음.'
  },
  {
    id: 'hospital-jungang-001',
    name: '중앙동물병원 후보',
    category: 'HOSPITAL',
    lat: 37.4444,
    lng: 127.1313,
    address: '경기 성남시 수정구 수정로 139 인근',
    description: '의료 연대 지점에 포함된 1차 응원 보건처.',
    dogFriendlyScore: 3,
    notes: '연륜 있는 진료 응대.'
  },
  {
    id: 'store-puppyparadise-001',
    name: '퍼피파라다이스 후보',
    category: 'PET_STORE',
    lat: 37.4581,
    lng: 127.1277,
    address: '경기 성남시 수정구 성남대로1380번길 11-2 인근',
    description: '복정동 전천후 생필품 및 고탄소 가슴 끈 보강 처소.',
    dogFriendlyScore: 3,
    notes: '간단 전용 물품 세일 다량 보유.'
  },
  {
    id: 'store-bnshop-001',
    name: '비앤샵 후보',
    category: 'PET_STORE',
    lat: 37.4560,
    lng: 127.1282,
    address: '경기 성남시 수정구 복정동 698 인근',
    description: '공원 근처 펫용 간식과 소라색 비를 피하는 펫의류 정밀점.',
    dogFriendlyScore: 3,
    notes: '수입 간식 상용 준비.'
  },
  {
    id: 'grooming-dogbarbershop-gyeon-001',
    name: '강아지이발소 견 후보',
    category: 'GROOMING',
    lat: 37.4561,
    lng: 127.1285,
    address: '경기 성남시 수정구 복정동 695-10 인근',
    description: '상처 없이 세련된 발바닥 미용과 가위 스파를 자초하는 명문 바버샵.',
    dogFriendlyScore: 4,
    notes: '성남 펫맘 가위컷 선호도 높음.'
  },
  {
    id: 'grooming-bokjeong-care-001',
    name: '복정동 반려견 미용 후보 지점',
    category: 'GROOMING',
    lat: 37.4570,
    lng: 127.1289,
    address: '경기 성남시 수정구 복정동 일대',
    description: '상큼한 개샴푸 향과 뽀송 진흙 펫 케어가 연동되는 예비 지점.',
    dogFriendlyScore: 3,
    notes: '전화 우선 예약 필수 권장.'
  },
  {
    id: 'park-gachon-campus-main-gate-001',
    name: '가천대 정문 산책 연결 지점',
    category: 'PARK',
    lat: 37.45075,
    lng: 127.12915,
    address: '경기 성남시 수정구 성남대로 1342 가천대학교',
    description: '정문 가로수단 그늘이 이색적인 대형 캠퍼스 동선 연결부.',
    dogFriendlyScore: 3,
    notes: '대학 로비 주변 소음 주의.'
  },
  {
    id: 'park-gachon-campus-south-loop-001',
    name: '가천대 남측 보행 연결 지점',
    category: 'PARK',
    lat: 37.44865,
    lng: 127.13015,
    address: '경기 성남시 수정구 성남대로 가천대학교 남측 인근',
    description: '수풀길 비탈면 아래 평평하게 벤치가 다람쥐 무늬로 세워진 길.',
    dogFriendlyScore: 3,
    notes: '노송 군락 그늘 양호.'
  },
  {
    id: 'park-gachon-campus-west-link-001',
    name: '가천대 서측 탄천 연결 지점',
    category: 'PARK',
    lat: 37.45005,
    lng: 127.12745,
    address: '가천대역·탄천 방향 보행 연결부',
    description: '수요 통행량이 적고 낙엽이 곱게 깔려 킁킁에 탁월한 연결 통로.',
    dogFriendlyScore: 4,
    notes: '가천대역 서편 계단과 연계.'
  },
  {
    id: 'park-gachon-station-exit1-plaza-001',
    name: '가천대역 1번출구 산책 시작 후보 지점',
    category: 'PARK',
    lat: 37.44895,
    lng: 127.12710,
    address: '가천대역 1번출구 인근',
    description: '약속 전후나 도보 이동 첫머리에 꼬리 흔들기 딱 좋은 마당 스팟.',
    dogFriendlyScore: 3,
    notes: '사람 통행 밀도가 높은 출퇴근 편차 유의.'
  },
  {
    id: 'park-gachon-station-exit2-link-001',
    name: '가천대역 서측 탄천 진입 후보 지점',
    category: 'PARK',
    lat: 37.44920,
    lng: 127.12570,
    address: '가천대역 서측·탄천 방향',
    description: '가천대역 엘리베이터로 유모차 안락 진입에 도움 되는 천변 통로.',
    dogFriendlyScore: 4,
    notes: '계단 대신 완만한 경사 경사판 완비.'
  },
  {
    id: 'park-tancheon-gachon-south-001',
    name: '탄천 가천대 남측 산책 지점',
    category: 'PARK',
    lat: 37.44720,
    lng: 127.12640,
    address: '가천대역 남측 탄천 산책로 인근',
    description: '갈대 바람이 살랑살랑 기지개에 쾌적한 안심 산책 정경.',
    dogFriendlyScore: 4,
    notes: '흙풀밭이 넓고 배변 시인성 양호.'
  },
  {
    id: 'park-tancheon-gachon-north-001',
    name: '탄천 가천대 북측 산책 지점',
    category: 'PARK',
    lat: 37.45200,
    lng: 127.12650,
    address: '가천대역 북측 탄천 산책로 인근',
    description: '복정동 교량까지 굴곡 없이 시원한 바람 속 보폭 조율 마당.',
    dogFriendlyScore: 4,
    notes: '보행선이 명료해 안전 달리기 우수.'
  },
  {
    id: 'park-tancheon-rodeo-link-001',
    name: '탄천 로데오거리 방향 연결 지점',
    category: 'PARK',
    lat: 37.45180,
    lng: 127.12480,
    address: '탄천·가천대 로데오거리 방향 연결부',
    description: '상권과 자연을 하이브리드로 즐기는 가교.',
    dogFriendlyScore: 3,
    notes: '식사 전 가벼운 용변 해결에 적합.'
  },
  {
    id: 'park-tancheon-taepyeong-north-001',
    name: '탄천 태평 북측 산책 지점',
    category: 'PARK',
    lat: 37.44300,
    lng: 127.12700,
    address: '태평동 탄천 산책로 북측 인근',
    description: '물소리가 우렁차고 소요 인적이 드물어 혼자 고무적인 명상 탐험에 적격.',
    dogFriendlyScore: 4,
    notes: '억새 마루 시야 웅장.'
  },
  {
    id: 'park-tancheon-taepyeong-south-001',
    name: '탄천 태평 남측 산책 지점',
    category: 'PARK',
    lat: 37.44050,
    lng: 127.12730,
    address: '태평역·탄천 산책로 남측 인근',
    description: '태평대교 아래 서늘한 자연 응달이 형성되는 노른자 마실처.',
    dogFriendlyScore: 4,
    notes: '여름철 최고 더위 대피령 구장.'
  },
  {
    id: 'park-tancheon-sujin-link-001',
    name: '탄천 수진 방향 산책 연결 지점',
    category: 'PARK',
    lat: 37.43890,
    lng: 127.12790,
    address: '수진동·탄천 산책로 인근',
    description: '수진 고수부지 체육공원 화단 화장실과 긴 수평 보도 연결 지대.',
    dogFriendlyScore: 3,
    notes: '장거리 철인 전용 코스.'
  },
  {
    id: 'park-bokjeong-station-south-link-001',
    name: '복정역 남측 산책 연결 지점',
    category: 'PARK',
    lat: 37.46930,
    lng: 127.12690,
    address: '복정역 남측 보행 연결부',
    description: '복정 환승역 주차동과 인접한 교통 중심형 펫 보행 터널 입구.',
    dogFriendlyScore: 3,
    notes: '소음 장벽이 설치되어 있음.'
  },
  {
    id: 'park-bokjeong-dongseoul-link-001',
    name: '복정동·동서울대 연결 산책 지점',
    category: 'PARK',
    lat: 37.46660,
    lng: 127.12850,
    address: '성남시 수정구 복정동 동서울대학교 인근',
    description: '대학 잔디 기획 마당과 복정천 도보를 연결하는 쾌적한 둥우리.',
    dogFriendlyScore: 3,
    notes: '캠퍼스 내 낙엽 정리 양호.'
  },
  {
    id: 'park-dongseoul-front-walk-001',
    name: '동서울대 앞 보행 산책 지점',
    category: 'PARK',
    lat: 37.45980,
    lng: 127.12810,
    address: '성남시 수정구 복정동 동서울대학교 앞 인근',
    description: '개성 넘치는 테이크아웃 카페들을 등지고 가볍게 소변을 누는 산골.',
    dogFriendlyScore: 3,
    notes: '인도 가로수 보강 구역.'
  },
  {
    id: 'park-bokjeong-residential-loop-001',
    name: '복정동 주거지 산책 루프 후보 지점',
    category: 'PARK',
    lat: 37.46180,
    lng: 127.12920,
    address: '성남시 수정구 복정동 주거지 인근',
    description: '주택가 안편의 가벼운 화단 장벽길. 반려 웰컴 성향 우수.',
    dogFriendlyScore: 3,
    notes: '주민들과 조우 시 긴밀 리드 조절.'
  },
  {
    id: 'park-sanseongdaero-sidewalk-001',
    name: '산성대로 보행 연결 산책 지점',
    category: 'PARK',
    lat: 37.45500,
    lng: 127.13000,
    address: '성남시 수정구 산성대로 인근',
    description: '대로변 수평 인도 및 메가 가로화 화단 설치 터.',
    dogFriendlyScore: 3,
    notes: '교통 통행 연선 주의.'
  },
  {
    id: 'park-taepyeong-rodeo-residential-001',
    name: '태평동 로데오거리 주거지 산책 지점',
    category: 'PARK',
    lat: 37.44480,
    lng: 127.12920,
    address: '성남시 수정구 태평동 로데오거리 인근',
    description: '시가지 근교의 작은 놀이터 화단들을 누비는 조용한 일주 코스.',
    dogFriendlyScore: 3,
    notes: '안전 보도 비중 높음.'
  },
  {
    id: 'park-tancheon-loop-return-001',
    name: '탄천 가천대 회귀 산책 지점',
    category: 'PARK',
    lat: 37.45490,
    lng: 127.12660,
    address: '가천대역 북측 탄천 산책로 인근',
    description: '둥근 유턴 슬로프로 하천 냄새를 골고루 맡고 역으로 리턴하는 귀로 스팟.',
    dogFriendlyScore: 4,
    notes: '돌아가기 전 시원한 벤치 그늘 집중.'
  },
  {
    id: 'toilet-gachon-station-public-001',
    name: '가천대역 공중화장실 및 배변 후보 지점',
    category: 'TOILET',
    lat: 37.44890,
    lng: 127.12695,
    address: '가천대역 인근 역사 대합실',
    description: '공중 전용 위생소. 보호자들의 급한 불 해결 및 휴지 구비 완비.',
    dogFriendlyScore: 3,
    notes: '반려견 안전 고리 있음.'
  },
  {
    id: 'toilet-gachon-campus-gate-candidate-001',
    name: '가천대 정문 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.45050,
    lng: 127.12885,
    address: '가천대학교 정문 가로수단 인근',
    description: '가천대 주말 출입 시 시 보급 청소 수배 핀.',
    dogFriendlyScore: 3,
    notes: '쓰레기통 다수 비치로 팩 투척 용이.'
  },
  {
    id: 'toilet-bokjeong-station-public-001',
    name: '복정역 공중화장실 및 배변 후보 지점',
    category: 'TOILET',
    lat: 37.47050,
    lng: 127.12680,
    address: '복정역 2번출구 인근',
    description: '쾌적한 환승역 전용 펫 위생 거점 후보지.',
    dogFriendlyScore: 3,
    notes: '청결도 우수 기조 유지.'
  },
  {
    id: 'toilet-dongseoul-front-candidate-001',
    name: '동서울대 앞 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.45960,
    lng: 127.12800,
    address: '성남시 수정구 복정동 동서울대학교 앞',
    description: '학교 화단 및 미화 봉사대 쓰레기 수거지 연결점.',
    dogFriendlyScore: 3,
    notes: '쓰레기 수거 연동 양호.'
  },
  {
    id: 'toilet-tancheon-taepyeong-candidate-001',
    name: '탄천 태평 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.44330,
    lng: 127.12720,
    address: '태평동 탄천 산책로 인근',
    description: '경유 산책 중 쓰레기를 폐기하고 발바닥 모래를 털 수 있는 슬롯 지점.',
    dogFriendlyScore: 3,
    notes: '상시 에티켓 청결 구비 요망.'
  },
  {
    id: 'toilet-tancheon-rodeo-candidate-001',
    name: '탄천 로데오거리 배변처리 후보 지점',
    category: 'TOILET',
    lat: 37.45160,
    lng: 127.12520,
    address: '가천대 로데오거리·탄천 연결부 인근',
    description: '상권 진입 전 마지막 냄새 털이 및 잔용 배변 에티켓 해결지.',
    dogFriendlyScore: 3,
    notes: '청소 도구 보충 완료.'
  }
];
